### ISSUE TITLE
Nuevo origen para no-laborables en España

### ISSUE THREAD

**Issue by jdlopez** [jdlopez/open-data#1]
Nuevo origen para no-laborables en España, comentado en: 
https://github.com/jdlopez/holydayapi/issues/8#issue-2014390193

> Buenas, puedes sacar el CSV con todos los festivos desde la propia web de la seguridad social:
> 
> https://www.seg-social.es/wps/PA_POINCALAB/CalendarioServlet?exportacion=CSV&tipo=0
> 
> También se puede filtrar por provincia o población para que el csv sea más pequeño, pero vamos, que ocupa menos de 60kb el completo.
> 
> Esta es la página de usuario donde está todo:
> 
> https://www.seg-social.es/wps/portal/wss/internet/CalendarioLaboral

**Comment by jdlopez** [comment]
Cargado el fichero

**Comment by acolombo11** [comment]
https://calendarios.ideal.es/ tiene los datos para muchos mas municipios, se sabe de donde los sacan?

**Comment by jdlopez** [comment]
Son de la editorial Vocento, a lo mejor tienen a algún becario mirándose los festivos locales +8000 localidades. Es una chufla que no haya una fuente única para todo, pero incluso los nacionales se publican como un PDF, así que mucho no se puede pedir :-(
